# Site settings
title: Huỳnh (Reino) Mai - a front-end developer
fullname: Huỳnh (Reino) Mai
email: maihuynh16995@gmail.com
phone: (+84) 946 607 797
description: Huỳnh (Reino) Mai, a front-end developer, based in Ben Tre, Vietnam.
baseurl: "/"
url: "https://reinowis.github.io"
keywords: "front-end, vietnam, developer, ben tre, mekong delta, angularjs, html, css, javascript"
intro: 
    highlight: I'm Huỳnh (Reino), a front-end developer based in Ben Tre, Vietnam. I'm passionate about traveling and reading.
    content: I have been working as a front-end developer for many years, constantly exploring new technologies and embracing fresh challenges every day.
# Social settings
social:
    -   label: github
        url: https://github.com/reinowis
    -   label: linkedin
        url: https://www.linkedin.com/in/huynh-reino-mai/
    -   label: behance
        url: https://www.behance.net/reinowis
# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
collections:
    portfolio:
        output: true
        permalink: /portfolio/:name
        layout: portfolio
defaults:
    -   scope:
            path: ""
            type: "portfolio"
        values:
            layout: "portfolio"
