# Site settings
title: Huynh (Reino) Mai - a front-end developer
fullnam: Huynh (Reino) Mai
email: maihuynh16995@gmail.com
phone: (+84) 946 607 797
description: Huynh (Reino) Mai, a front-end developer, based in HCMC, Vietnam.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://reinowis.github.io" # the base hostname & protocol for your site

# Social settings
500px_url:
# facebook_url: https://facebook.com
github_url: https://github.com/reinowis
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
# instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/huynh-reino-mai/
pinterest_url:
slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
collections:
    portfolio:
        output: true
        permalink: /portfolio/:name
        layout: portfolio
defaults:
    -   scope:
            path: ""
            type: "portfolio"
        values:
            layout: "portfolio"