# Site settings
title: Huynh (Reino) Mai - a front-end developer
fullname: Huynh (Reino) Mai
email: maihuynh16995@gmail.com
phone: (+84) 946 607 797
description: Huynh (Reino) Mai, a front-end developer, based in HCMC, Vietnam.
baseurl: "/"
url: "https://reinowis.github.io"
keywords: "front-end, vietnam, developer, ben tre, mekong delta, angularjs, html, css, javascript"
intro: 
    highlight: I'm Reino, a front-end developer based in HCMC, Vietnam. Traveling & reading are my favorite hobbies.
    content: I have been working as a front-end developer for 3 years. i'm always eagle for not only learning the new things about front-end technologies, but also the new challenges everyday. 
# Social settings
social:
    -   label: github
        url: https://github.com/reinowis
    -   label: linkedin
        url: https://www.linkedin.com/in/huynh-reino-mai/
    -   label: behance
        url: https://www.behance.net/reinowis
    -   label: skype
        url: "skype:mousewis"
# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
collections:
    portfolio:
        output: true
        permalink: /portfolio/:name
        layout: portfolio
defaults:
    -   scope:
            path: ""
            type: "portfolio"
        values:
            layout: "portfolio"